### ISSUE TITLE
Error(No module named '_cffi_backend')

### ISSUE THREAD

**Issue by skertz** [mediro-ict/activegate_python_ssl_plugin#4]
After an auto update on Dynarace Active gate from 1.229.168 to 1.231.246, this error is now occurring.
Error(No module named '_cffi_backend')

This happened from logfiles at the exact time to stop monitoring the cert endpoints at the time, AG was updated and restarted.

**Comment by leonvzGit** [comment]
Hi @skertz , this is related to https://www.dynatrace.com/support/help/technology-support/dynatrace-extensions#dynatrace-extension-framework-upgrade-notice
I will have to recompile the extension with python 3.8. look out for a new release soon.

**Comment by leonvzGit** [comment]
The new release :https://github.com/mediro-ict/activegate_python_ssl_plugin/releases/tag/v1.020 fixes this problem
