### ISSUE TITLE
Extension goes to uninitiated at intervals.

### ISSUE THREAD

**Issue by MamaAfrica** [mediro-ict/activegate_python_ssl_plugin#6]
Hi, Please is there a limit to the number of domains the extension can monitor? I have up to 50 domains I would like to check their certificates. I noticed after setting up a few of them, the extension comes on and off. Also the metric ext:tech.CertificateCheck.counter is not showing any data on dynatrace only the Days before expiration has data.

**Comment by leonvzGit** [comment]
Hi Please add the logs so we can investigate

**Comment by MamaAfrica** [comment]
[CertsPluginRemote.log](https://github.com/mediro-ict/activegate_python_ssl_plugin/files/11068286/CertsPluginRemote.log)
[ruxitagent_remotepluginagent_66513.0.log](https://github.com/mediro-ict/activegate_python_ssl_plugin/files/11068288/ruxitagent_remotepluginagent_66513.0.log)

Hi Leon, Please find attached the log files. 
Thanks for the suggestion.
